[build]
publish = "public"
command = "ls -l public/index.html"

[[redirects]]
  from = "https://crashloopbackoff.netlify.com/*"
  to = "https://crashloopbackoff.dev/:splat"
  status = 301
  force = true